-- Chat Jr — esquema inicial.
-- Escrito em SQL padrão para rodar igual em PostgreSQL (produção) e H2 em modo PostgreSQL (desenvolvimento).
-- Nenhuma credencial entra em migração: contas de demonstração são criadas por código, no perfil "demo".

CREATE TABLE client_account (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role              VARCHAR(10)  NOT NULL,
    name              VARCHAR(120) NOT NULL,
    email             VARCHAR(200) NOT NULL,
    password_hash     VARCHAR(100),
    company           VARCHAR(160),
    segment           VARCHAR(120),
    plan_version      INTEGER      NOT NULL DEFAULT 0,
    plan_file         VARCHAR(255),
    plan_updated_at   TIMESTAMP WITH TIME ZONE,
    suspended         BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_attempts   INTEGER      NOT NULL DEFAULT 0,
    first_failed_at   TIMESTAMP WITH TIME ZONE,
    locked_until      TIMESTAMP WITH TIME ZONE,
    token_hash        VARCHAR(64),
    token_purpose     VARCHAR(10),
    token_expires_at  TIMESTAMP WITH TIME ZONE,
    last_login_at     TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_account_email UNIQUE (email),
    CONSTRAINT ck_account_role CHECK (role IN ('ADMIN', 'CLIENT')),
    CONSTRAINT ck_account_token_purpose CHECK (token_purpose IS NULL OR token_purpose IN ('INVITE', 'RESET'))
);
CREATE INDEX ix_account_token ON client_account (token_hash);

CREATE TABLE plan_tab (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            BIGINT        NOT NULL,
    slug                 VARCHAR(120)  NOT NULL,
    name                 VARCHAR(160)  NOT NULL,
    title                VARCHAR(200)  NOT NULL,
    sort_order           INTEGER       NOT NULL DEFAULT 0,
    html                 VARCHAR(1000000) NOT NULL DEFAULT '',
    published            BOOLEAN       NOT NULL DEFAULT TRUE,
    content_version      INTEGER       NOT NULL DEFAULT 0,
    short_description    VARCHAR(500),
    what_is_it           VARCHAR(2000),
    objective            VARCHAR(2000),
    key_points           VARCHAR(4000),
    suggested_questions  VARCHAR(2000),
    source_label         VARCHAR(500),
    content_updated_at   TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tab_client FOREIGN KEY (client_id) REFERENCES client_account (id) ON DELETE CASCADE,
    CONSTRAINT uq_tab_slug UNIQUE (client_id, slug)
);
CREATE INDEX ix_tab_client ON plan_tab (client_id, sort_order);

CREATE TABLE attachment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_id              BIGINT       NOT NULL,
    pdf_name            VARCHAR(255),
    pdf_text            VARCHAR(1000000),
    pdf_chars           INTEGER      NOT NULL DEFAULT 0,
    pdf_pages           INTEGER      NOT NULL DEFAULT 0,
    stored_path         VARCHAR(500),
    stored_bytes        BIGINT       NOT NULL DEFAULT 0,
    slide_link          VARCHAR(1000),
    state               VARCHAR(12)  NOT NULL DEFAULT 'IDLE',
    processed           BOOLEAN      NOT NULL DEFAULT FALSE,
    extracted_sections  INTEGER      NOT NULL DEFAULT 0,
    sections            VARCHAR(4000),
    knowledge           VARCHAR(1000000),
    processed_at        TIMESTAMP WITH TIME ZONE,
    error_message       VARCHAR(1000),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_attachment_tab UNIQUE (tab_id),
    CONSTRAINT fk_attachment_tab FOREIGN KEY (tab_id) REFERENCES plan_tab (id) ON DELETE CASCADE,
    CONSTRAINT ck_attachment_state CHECK (state IN ('IDLE', 'PROCESSING', 'DONE', 'FAILED'))
);

-- Trechos do conhecimento de cada aba; a busca por relevância (BM25) roda sobre eles.
CREATE TABLE tab_chunk (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_id       BIGINT        NOT NULL,
    chunk_index  INTEGER       NOT NULL,
    content      VARCHAR(8000) NOT NULL,
    CONSTRAINT uq_chunk UNIQUE (tab_id, chunk_index),
    CONSTRAINT fk_chunk_tab FOREIGN KEY (tab_id) REFERENCES plan_tab (id) ON DELETE CASCADE
);

-- Cada processamento guarda o estado anterior da aba, para poder restaurar.
CREATE TABLE plan_version (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_id               BIGINT       NOT NULL,
    version              INTEGER      NOT NULL,
    title                VARCHAR(200) NOT NULL,
    html                 VARCHAR(1000000) NOT NULL,
    short_description    VARCHAR(500),
    what_is_it           VARCHAR(2000),
    objective            VARCHAR(2000),
    key_points           VARCHAR(4000),
    suggested_questions  VARCHAR(2000),
    reason               VARCHAR(40)  NOT NULL,
    created_by           VARCHAR(200),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_plan_version UNIQUE (tab_id, version),
    CONSTRAINT fk_version_tab FOREIGN KEY (tab_id) REFERENCES plan_tab (id) ON DELETE CASCADE
);

-- Escopo: linha ausente significa "liberada".
CREATE TABLE tab_scope (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT  NOT NULL,
    tab_id     BIGINT  NOT NULL,
    allowed    BOOLEAN NOT NULL,
    CONSTRAINT uq_scope UNIQUE (client_id, tab_id),
    CONSTRAINT fk_scope_client FOREIGN KEY (client_id) REFERENCES client_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_scope_tab FOREIGN KEY (tab_id) REFERENCES plan_tab (id) ON DELETE CASCADE
);

CREATE TABLE conversation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT       NOT NULL,
    title       VARCHAR(200) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_conversation_client FOREIGN KEY (client_id) REFERENCES client_account (id) ON DELETE CASCADE
);
CREATE INDEX ix_conversation_client ON conversation (client_id, updated_at);

CREATE TABLE chat_message (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT        NOT NULL,
    role             VARCHAR(4)    NOT NULL,
    html             VARCHAR(100000) NOT NULL,
    source           VARCHAR(200),
    inference        BOOLEAN       NOT NULL DEFAULT FALSE,
    degraded         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_message_role CHECK (role IN ('USER', 'AI')),
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE
);
CREATE INDEX ix_message_conversation ON chat_message (conversation_id, id);

-- Base dos indicadores. Sem chave estrangeira para a conversa: apagar a conversa não apaga a estatística.
CREATE TABLE query_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id        BIGINT       NOT NULL,
    conversation_id  BIGINT,
    question         VARCHAR(500) NOT NULL,
    query_type       VARCHAR(14)  NOT NULL,
    answered         BOOLEAN      NOT NULL,
    source_tab_id    BIGINT,
    theme            VARCHAR(160),
    degraded         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_query_client FOREIGN KEY (client_id) REFERENCES client_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_query_type CHECK (query_type IN ('INFORMACAO', 'DUVIDA', 'INTERPRETACAO', 'DECISAO'))
);
CREATE INDEX ix_query_client ON query_log (client_id, created_at);

CREATE TABLE app_setting (
    setting_key    VARCHAR(100) PRIMARY KEY,
    setting_value  VARCHAR(4000),
    secret         BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Sem chaves estrangeiras: o histórico precisa sobreviver à exclusão de clientes e abas.
CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT,
    actor_email  VARCHAR(200),
    client_id    BIGINT,
    action       VARCHAR(40) NOT NULL,
    tab_id       BIGINT,
    tab_name     VARCHAR(160),
    detail       VARCHAR(1000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_client ON audit_log (client_id, created_at);
CREATE INDEX ix_audit_created ON audit_log (created_at);

CREATE TABLE ai_call_log (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          BIGINT,
    kind               VARCHAR(10) NOT NULL,
    model              VARCHAR(80),
    status             VARCHAR(10) NOT NULL,
    http_status        INTEGER,
    duration_ms        INTEGER,
    input_tokens       INTEGER,
    output_tokens      INTEGER,
    est_cost_microusd  BIGINT,
    error_message      VARCHAR(500),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_ai_call_created ON ai_call_log (created_at);

CREATE TABLE app_error (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message     VARCHAR(1000) NOT NULL,
    path        VARCHAR(300),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
