-- Pedidos de acesso feitos pela landing (defeito 12): a pessoa deixa o contato, a consultoria decide se cria o acesso.
CREATE TABLE access_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,
    email        VARCHAR(200) NOT NULL,
    company      VARCHAR(160) NOT NULL,
    phone        VARCHAR(40),
    message      VARCHAR(1000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    handled_at   TIMESTAMP WITH TIME ZONE,
    handled_by   VARCHAR(200)
);
CREATE INDEX ix_access_request_open ON access_request (handled_at, created_at);
